/** Level-ordered combat cues. Timings/roles mirror engine/src/boss_attacks.rs. */
export const BOSS_ATTACKS = [
  {
    name: "Override rails",
    dodge: "Step between the paired rails",
    weak: "Precision",
    windup: 1.0,
    recovery: 1.5,
  },
  {
    name: "Forge cutter",
    dodge: "Clear the parallel cutter lanes",
    weak: "Shock",
    windup: 1.2,
    recovery: 1.8,
  },
  {
    name: "Corrosive bloom",
    dodge: "Strafe clear of the acid cluster",
    weak: "Burn",
    windup: 1.1,
    recovery: 1.6,
  },
  {
    name: "Predictor cross",
    dodge: "Move away from the crossing lanes",
    weak: "Control",
    windup: 1.0,
    recovery: 1.5,
  },
  {
    name: "Sink capture",
    dodge: "Leave the marked gravity disk",
    weak: "Blast",
    windup: 1.3,
    recovery: 1.9,
  },
  {
    name: "Archive braid",
    dodge: "Keep moving through the alternating rails",
    weak: "Precision",
    windup: 1.1,
    recovery: 1.6,
  },
  {
    name: "Rime crescent",
    dodge: "Break sight to avoid the cryo fan",
    weak: "Burn",
    windup: 1.2,
    recovery: 1.7,
  },
  {
    name: "Relay cascade",
    dodge: "Strafe across the shock lanes",
    weak: "Stagger",
    windup: 0.9,
    recovery: 1.5,
  },
  {
    name: "Titan siege",
    dodge: "Leave the converging ordnance lanes",
    weak: "Precision",
    windup: 1.4,
    recovery: 2.0,
  },
  {
    name: "Kest triplet",
    dodge: "Keep strafing through all three pulses",
    weak: "Suppress",
    windup: 1.0,
    recovery: 1.5,
  },
  {
    name: "Memory echoes",
    dodge: "Wait for the slower trailing echoes",
    weak: "Shock",
    windup: 1.3,
    recovery: 1.9,
  },
  {
    name: "Cinder fork",
    dodge: "Move between the split incendiary lanes",
    weak: "Freeze",
    windup: 1.2,
    recovery: 1.7,
  },
  {
    name: "Undertow surge",
    dodge: "Watch for the faster pressure harpoons",
    weak: "Shock",
    windup: 1.2,
    recovery: 1.8,
  },
  {
    name: "Spectrum lattice",
    dodge: "Move out of the converging prism lanes",
    weak: "Stagger",
    windup: 1.1,
    recovery: 1.6,
  },
  {
    name: "Polarity capture",
    dodge: "Leave the magnetic target disk",
    weak: "Acid",
    windup: 1.3,
    recovery: 1.9,
  },
  {
    name: "Hatchery deployment",
    dodge: "Dodge the spokes; clear the spawned drone",
    weak: "Blast",
    windup: 1.4,
    recovery: 2.0,
  },
  {
    name: "Spore drift",
    dodge: "Clear the slow drifting spore cloud",
    weak: "Burn",
    windup: 1.3,
    recovery: 1.8,
  },
  {
    name: "Starfall array",
    dodge: "Keep moving past the staggered missiles",
    weak: "Precision",
    windup: 1.4,
    recovery: 2.0,
  },
  {
    name: "Reclaimer comb",
    dodge: "Clear the wide flechette wall",
    weak: "Shock",
    windup: 1.1,
    recovery: 1.6,
  },
  {
    name: "Veil ambush",
    dodge: "Leave the marked position before the jump",
    weak: "Control",
    windup: 1.2,
    recovery: 1.8,
  },
  {
    name: "Helios corona",
    dodge: "Use the gap directly ahead of the boss",
    weak: "Freeze",
    windup: 1.4,
    recovery: 2.0,
  },
  {
    name: "Torpedo pincer",
    dodge: "Clear both converging torpedo paths",
    weak: "Precision",
    windup: 1.3,
    recovery: 1.9,
  },
  {
    name: "Epoch tripwire",
    dodge: "Dodge the fast pulse and trailing echoes",
    weak: "Suppress",
    windup: 1.3,
    recovery: 1.8,
  },
  {
    name: "Glacier chevron",
    dodge: "Leave the ice chevron before impact",
    weak: "Burn",
    windup: 1.4,
    recovery: 2.0,
  },
  {
    name: "Dominion command",
    dodge: "Dodge the alternating salvo; clear the escort",
    weak: "Shock",
    windup: 1.5,
    recovery: 2.1,
  },
] as const;

export function bossAttackForWave(wave: number) {
  return BOSS_ATTACKS[(Math.max(1, Math.trunc(wave)) - 1) % BOSS_ATTACKS.length];
}
