export const SECTOR_ENEMIES = [
  {
    skin: 37,
    slug: "sector-upper-works",
    name: "Tunnel Warden",
    level: 1,
    base: 0,
  },
  {
    skin: 38,
    slug: "sector-cryogenic-foundry",
    name: "Frost Welder",
    level: 2,
    base: 3,
  },
  {
    skin: 39,
    slug: "sector-bioforge-depths",
    name: "Culture Keeper",
    level: 3,
    base: 10,
  },
  {
    skin: 40,
    slug: "sector-data-spine",
    name: "Network Sentinel",
    level: 4,
    base: 7,
  },
  {
    skin: 41,
    slug: "sector-reactor-sink",
    name: "Containment Trooper",
    level: 5,
    base: 3,
  },
  {
    skin: 42,
    slug: "sector-null-archive",
    name: "Tape Custodian",
    level: 6,
    base: 0,
  },
  {
    skin: 43,
    slug: "sector-cryo-reserve",
    name: "Cryo Handler",
    level: 7,
    base: 3,
  },
  {
    skin: 44,
    slug: "sector-signal-crypt",
    name: "Signal Interceptor",
    level: 8,
    base: 7,
  },
  {
    skin: 45,
    slug: "sector-siege-yard",
    name: "Siege Rigger",
    level: 9,
    base: 4,
  },
  {
    skin: 46,
    slug: "sector-command-bunker",
    name: "Command Enforcer",
    level: 10,
    base: 1,
  },
  {
    skin: 47,
    slug: "sector-obsidian-vault",
    name: "Vault Watcher",
    level: 11,
    base: 7,
  },
  {
    skin: 48,
    slug: "sector-ashen-transit",
    name: "Railbreaker",
    level: 12,
    base: 1,
  },
  {
    skin: 49,
    slug: "sector-tidal-pumpstation",
    name: "Pressure Diver",
    level: 13,
    base: 3,
  },
  {
    skin: 50,
    slug: "sector-optics-array",
    name: "Lens Defender",
    level: 14,
    base: 7,
  },
  {
    skin: 51,
    slug: "sector-magnetic-forge",
    name: "Coil Technician",
    level: 15,
    base: 4,
  },
  {
    skin: 52,
    slug: "sector-drone-hatchery",
    name: "Hive Tender",
    level: 16,
    base: 8,
  },
  {
    skin: 53,
    slug: "sector-fungal-research",
    name: "Spore Host",
    level: 17,
    base: 10,
  },
  {
    skin: 54,
    slug: "sector-orbital-uplink",
    name: "Uplink Ranger",
    level: 18,
    base: 7,
  },
  {
    skin: 55,
    slug: "sector-waste-reclaimer",
    name: "Scrap Mauler",
    level: 19,
    base: 5,
  },
  {
    skin: 56,
    slug: "sector-shadow-lab",
    name: "Phase Stalker",
    level: 20,
    base: 2,
  },
  {
    skin: 57,
    slug: "sector-fusion-chamber",
    name: "Fusion Keeper",
    level: 21,
    base: 3,
  },
  {
    skin: 58,
    slug: "sector-flooded-silo",
    name: "Silo Diver",
    level: 22,
    base: 3,
  },
  {
    skin: 59,
    slug: "sector-chrono-archive",
    name: "Chrono Curator",
    level: 23,
    base: 7,
  },
  {
    skin: 60,
    slug: "sector-black-ice-core",
    name: "Icecore Sentinel",
    level: 24,
    base: 8,
  },
  {
    skin: 61,
    slug: "sector-apex-control",
    name: "Apex Praetorian",
    level: 25,
    base: 4,
  },
] as const;
export function enemyCombatSkin(skin: number): number {
  return SECTOR_ENEMIES[skin - 37]?.base ?? skin;
}
